// 权限常量定义 - 与数据库种子文件保持一致
export const PERMISSIONS = {
  // 系统管理权限
  TENANT_VIEW: "TENANT_VIEW",
  TENANT_CREATE: "TENANT_CREATE",
  TENANT_EDIT: "TENANT_EDIT",
  TENANT_DELETE: "TENANT_DELETE",

  DEPARTMENT_VIEW: "DEPARTMENT_VIEW",
  DEPARTMENT_CREATE: "DEPARTMENT_CREATE",
  DEPARTMENT_EDIT: "DEPARTMENT_EDIT",
  DEPARTMENT_DELETE: "DEPARTMENT_DELETE",

  USER_VIEW: "USER_VIEW",
  USER_CREATE: "USER_CREATE",
  USER_EDIT: "USER_EDIT",
  USER_DELETE: "USER_DELETE",

  ROLE_VIEW: "ROLE_VIEW",
  ROLE_CREATE: "ROLE_CREATE",
  ROLE_EDIT: "ROLE_EDIT",
  ROLE_DELETE: "ROLE_DELETE",

  PERMISSION_VIEW: "PERMISSION_VIEW",
  PERMISSION_CREATE: "PERMISSION_CREATE",
  PERMISSION_EDIT: "PERMISSION_EDIT",
  PERMISSION_DELETE: "PERMISSION_DELETE",

  // 认证相关
  ACCOUNT_VIEW: "ACCOUNT_VIEW",
  ACCOUNT_CREATE: "ACCOUNT_CREATE",
  ACCOUNT_EDIT: "ACCOUNT_EDIT",
  ACCOUNT_DELETE: "ACCOUNT_DELETE",

  SESSION_VIEW: "SESSION_VIEW",
  SESSION_CREATE: "SESSION_CREATE",
  SESSION_EDIT: "SESSION_EDIT",
  SESSION_DELETE: "SESSION_DELETE",

  VERIFICATION_VIEW: "VERIFICATION_VIEW",
  VERIFICATION_CREATE: "VERIFICATION_CREATE",
  VERIFICATION_EDIT: "VERIFICATION_EDIT",
  VERIFICATION_DELETE: "VERIFICATION_DELETE",

  // 站点相关
  SITE_VIEW: "SITE_VIEW",
  SITE_CREATE: "SITE_CREATE",
  SITE_EDIT: "SITE_EDIT",
  SITE_DELETE: "SITE_DELETE",

  SITECATEGORY_VIEW: "SITECATEGORY_VIEW",
  SITECATEGORY_CREATE: "SITECATEGORY_CREATE",
  SITECATEGORY_EDIT: "SITECATEGORY_EDIT",
  SITECATEGORY_DELETE: "SITECATEGORY_DELETE",

  SITEPRODUCT_VIEW: "SITEPRODUCT_VIEW",
  SITEPRODUCT_CREATE: "SITEPRODUCT_CREATE",
  SITEPRODUCT_EDIT: "SITEPRODUCT_EDIT",
  SITEPRODUCT_DELETE: "SITEPRODUCT_DELETE",

  SITECONFIG_VIEW: "SITECONFIG_VIEW",
  SITECONFIG_CREATE: "SITECONFIG_CREATE",
  SITECONFIG_EDIT: "SITECONFIG_EDIT",
  SITECONFIG_DELETE: "SITECONFIG_DELETE",

  // 分类和模板
  MASTERCATEGORY_VIEW: "MASTERCATEGORY_VIEW",
  MASTERCATEGORY_CREATE: "MASTERCATEGORY_CREATE",
  MASTERCATEGORY_EDIT: "MASTERCATEGORY_EDIT",
  MASTERCATEGORY_DELETE: "MASTERCATEGORY_DELETE",

  TEMPLATE_VIEW: "TEMPLATE_VIEW",
  TEMPLATE_CREATE: "TEMPLATE_CREATE",
  TEMPLATE_EDIT: "TEMPLATE_EDIT",
  TEMPLATE_DELETE: "TEMPLATE_DELETE",

  TEMPLATEKEY_VIEW: "TEMPLATEKEY_VIEW",
  TEMPLATEKEY_CREATE: "TEMPLATEKEY_CREATE",
  TEMPLATEKEY_EDIT: "TEMPLATEKEY_EDIT",
  TEMPLATEKEY_DELETE: "TEMPLATEKEY_DELETE",

  TEMPLATEVALUE_VIEW: "TEMPLATEVALUE_VIEW",
  TEMPLATEVALUE_CREATE: "TEMPLATEVALUE_CREATE",
  TEMPLATEVALUE_EDIT: "TEMPLATEVALUE_EDIT",
  TEMPLATEVALUE_DELETE: "TEMPLATEVALUE_DELETE",

  // 产品相关
  PRODUCT_VIEW: "PRODUCT_VIEW",
  PRODUCT_CREATE: "PRODUCT_CREATE",
  PRODUCT_EDIT: "PRODUCT_EDIT",
  PRODUCT_DELETE: "PRODUCT_DELETE",

  PRODUCTMASTERCATEGORY_VIEW: "PRODUCTMASTERCATEGORY_VIEW",
  PRODUCTMASTERCATEGORY_CREATE: "PRODUCTMASTERCATEGORY_CREATE",
  PRODUCTMASTERCATEGORY_EDIT: "PRODUCTMASTERCATEGORY_EDIT",
  PRODUCTMASTERCATEGORY_DELETE: "PRODUCTMASTERCATEGORY_DELETE",

  PRODUCTSITECATEGORY_VIEW: "PRODUCTSITECATEGORY_VIEW",
  PRODUCTSITECATEGORY_CREATE: "PRODUCTSITECATEGORY_CREATE",
  PRODUCTSITECATEGORY_EDIT: "PRODUCTSITECATEGORY_EDIT",
  PRODUCTSITECATEGORY_DELETE: "PRODUCTSITECATEGORY_DELETE",

  PRODUCTMEDIA_VIEW: "PRODUCTMEDIA_VIEW",
  PRODUCTMEDIA_CREATE: "PRODUCTMEDIA_CREATE",
  PRODUCTMEDIA_EDIT: "PRODUCTMEDIA_EDIT",
  PRODUCTMEDIA_DELETE: "PRODUCTMEDIA_DELETE",

  PRODUCTTEMPLATE_VIEW: "PRODUCTTEMPLATE_VIEW",
  PRODUCTTEMPLATE_CREATE: "PRODUCTTEMPLATE_CREATE",
  PRODUCTTEMPLATE_EDIT: "PRODUCTTEMPLATE_EDIT",
  PRODUCTTEMPLATE_DELETE: "PRODUCTTEMPLATE_DELETE",

  SKU_VIEW: "SKU_VIEW",
  SKU_CREATE: "SKU_CREATE",
  SKU_EDIT: "SKU_EDIT",
  SKU_DELETE: "SKU_DELETE",

  SKUMEDIA_VIEW: "SKUMEDIA_VIEW",
  SKUMEDIA_CREATE: "SKUMEDIA_CREATE",
  SKUMEDIA_EDIT: "SKUMEDIA_EDIT",
  SKUMEDIA_DELETE: "SKUMEDIA_DELETE",

  // 媒体相关
  MEDIA_VIEW: "MEDIA_VIEW",
  MEDIA_CREATE: "MEDIA_CREATE",
  MEDIA_EDIT: "MEDIA_EDIT",
  MEDIA_DELETE: "MEDIA_DELETE",

  MEDIAMETADATA_VIEW: "MEDIAMETADATA_VIEW",
  MEDIAMETADATA_CREATE: "MEDIAMETADATA_CREATE",
  MEDIAMETADATA_EDIT: "MEDIAMETADATA_EDIT",
  MEDIAMETADATA_DELETE: "MEDIAMETADATA_DELETE",

  // 广告和首页
  AD_VIEW: "AD_VIEW",
  AD_CREATE: "AD_CREATE",
  AD_EDIT: "AD_EDIT",
  AD_DELETE: "AD_DELETE",

  HEROCARD_VIEW: "HEROCARD_VIEW",
  HEROCARD_CREATE: "HEROCARD_CREATE",
  HEROCARD_EDIT: "HEROCARD_EDIT",
  HEROCARD_DELETE: "HEROCARD_DELETE",

  // 业务表
  CUSTOMER_VIEW: "CUSTOMER_VIEW",
  CUSTOMER_CREATE: "CUSTOMER_CREATE",
  CUSTOMER_EDIT: "CUSTOMER_EDIT",
  CUSTOMER_DELETE: "CUSTOMER_DELETE",

  INQUIRY_VIEW: "INQUIRY_VIEW",
  INQUIRY_CREATE: "INQUIRY_CREATE",
  INQUIRY_EDIT: "INQUIRY_EDIT",
  INQUIRY_DELETE: "INQUIRY_DELETE",

  QUOTATION_VIEW: "QUOTATION_VIEW",
  QUOTATION_CREATE: "QUOTATION_CREATE",
  QUOTATION_EDIT: "QUOTATION_EDIT",
  QUOTATION_DELETE: "QUOTATION_DELETE",

  DAILYINQUIRYCOUNTER_VIEW: "DAILYINQUIRYCOUNTER_VIEW",
  DAILYINQUIRYCOUNTER_CREATE: "DAILYINQUIRYCOUNTER_CREATE",
  DAILYINQUIRYCOUNTER_EDIT: "DAILYINQUIRYCOUNTER_EDIT",
  DAILYINQUIRYCOUNTER_DELETE: "DAILYINQUIRYCOUNTER_DELETE",

  // 特殊权限
  SITES_MANAGE: "SITES_MANAGE",
  TENANTS_MANAGE: "TENANTS_MANAGE",

  // 超级管理员权限（通配符）
  SUPER: "*",
} as const;

// 权限分组
export const PERMISSION_GROUPS = {
  // 系统管理相关权限
  SYSTEM_MANAGEMENT: [
    PERMISSIONS.TENANT_VIEW,
    PERMISSIONS.TENANT_CREATE,
    PERMISSIONS.TENANT_EDIT,
    PERMISSIONS.TENANT_DELETE,
    PERMISSIONS.DEPARTMENT_VIEW,
    PERMISSIONS.DEPARTMENT_CREATE,
    PERMISSIONS.DEPARTMENT_EDIT,
    PERMISSIONS.DEPARTMENT_DELETE,
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_EDIT,
    PERMISSIONS.USER_DELETE,
    PERMISSIONS.ROLE_VIEW,
    PERMISSIONS.ROLE_CREATE,
    PERMISSIONS.ROLE_EDIT,
    PERMISSIONS.ROLE_DELETE,
    PERMISSIONS.PERMISSION_VIEW,
    PERMISSIONS.PERMISSION_CREATE,
    PERMISSIONS.PERMISSION_EDIT,
    PERMISSIONS.PERMISSION_DELETE,
    PERMISSIONS.TENANTS_MANAGE,
  ],

  // 用户管理相关权限
  USER_MANAGEMENT: [
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_EDIT,
    PERMISSIONS.USER_DELETE,
  ],

  // 产品管理相关权限
  PRODUCT_MANAGEMENT: [
    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.PRODUCT_CREATE,
    PERMISSIONS.PRODUCT_EDIT,
    PERMISSIONS.PRODUCT_DELETE,
    PERMISSIONS.SKU_VIEW,
    PERMISSIONS.SKU_CREATE,
    PERMISSIONS.SKU_EDIT,
    PERMISSIONS.SKU_DELETE,
    PERMISSIONS.MASTERCATEGORY_VIEW,
    PERMISSIONS.MASTERCATEGORY_CREATE,
    PERMISSIONS.MASTERCATEGORY_EDIT,
    PERMISSIONS.MASTERCATEGORY_DELETE,
    PERMISSIONS.TEMPLATE_VIEW,
    PERMISSIONS.TEMPLATE_CREATE,
    PERMISSIONS.TEMPLATE_EDIT,
    PERMISSIONS.TEMPLATE_DELETE,
    PERMISSIONS.MEDIA_VIEW,
    PERMISSIONS.MEDIA_CREATE,
    PERMISSIONS.MEDIA_EDIT,
    PERMISSIONS.MEDIA_DELETE,
  ],

  // 订单和业务管理权限
  BUSINESS_MANAGEMENT: [
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_EDIT,
    PERMISSIONS.CUSTOMER_DELETE,
    PERMISSIONS.INQUIRY_VIEW,
    PERMISSIONS.INQUIRY_CREATE,
    PERMISSIONS.INQUIRY_EDIT,
    PERMISSIONS.INQUIRY_DELETE,
    PERMISSIONS.QUOTATION_VIEW,
    PERMISSIONS.QUOTATION_CREATE,
    PERMISSIONS.QUOTATION_EDIT,
    PERMISSIONS.QUOTATION_DELETE,
  ],

  // 内容管理相关权限
  CONTENT_MANAGEMENT: [
    PERMISSIONS.HEROCARD_VIEW,
    PERMISSIONS.HEROCARD_CREATE,
    PERMISSIONS.HEROCARD_EDIT,
    PERMISSIONS.HEROCARD_DELETE,
    PERMISSIONS.AD_VIEW,
    PERMISSIONS.AD_CREATE,
    PERMISSIONS.AD_EDIT,
    PERMISSIONS.AD_DELETE,
  ],

  // 站点管理相关权限
  SITE_MANAGEMENT: [
    PERMISSIONS.SITE_VIEW,
    PERMISSIONS.SITE_CREATE,
    PERMISSIONS.SITE_EDIT,
    PERMISSIONS.SITE_DELETE,
    PERMISSIONS.SITECATEGORY_VIEW,
    PERMISSIONS.SITECATEGORY_CREATE,
    PERMISSIONS.SITECATEGORY_EDIT,
    PERMISSIONS.SITECATEGORY_DELETE,
    PERMISSIONS.SITECONFIG_VIEW,
    PERMISSIONS.SITECONFIG_CREATE,
    PERMISSIONS.SITECONFIG_EDIT,
    PERMISSIONS.SITECONFIG_DELETE,
    PERMISSIONS.SITES_MANAGE,
  ],
} as const;

// 角色定义 - 与数据库种子文件保持一致
export const ROLES = {
  SUPER_ADMIN: "super_admin",
  TENANT_ADMIN: "tenant_admin",
  DEPT_MANAGER: "dept_manager",
  SALESPERSON: "salesperson",
} as const;

// 角色显示名称
export const ROLE_LABELS: Record<string, string> = {
  [ROLES.SUPER_ADMIN]: "超级管理员",
  [ROLES.TENANT_ADMIN]: "租户管理员",
  [ROLES.DEPT_MANAGER]: "部门经理",
  [ROLES.SALESPERSON]: "业务员",
} as const;

// 角色描述
export const ROLE_DESCRIPTIONS: Record<string, string> = {
  [ROLES.SUPER_ADMIN]: "拥有所有权限的超级管理员",
  [ROLES.TENANT_ADMIN]: "租户级别的管理员，管理租户下的所有资源",
  [ROLES.DEPT_MANAGER]: "部门经理，管理本部门及子部门的资源",
  [ROLES.SALESPERSON]: "业务员，负责客户和询盘管理",
} as const;

// 角色默认权限配置 - 与数据库种子文件保持一致
export const ROLE_PERMISSIONS: Record<string, string[]> = {
  [ROLES.SUPER_ADMIN]: [PERMISSIONS.SUPER],

  [ROLES.TENANT_ADMIN]: [
    // 系统用户管理
    ...generateCRUDPermissions("SYS_USERS"),
    ...generateCRUDPermissions("SYS_DEPTS"),
    // 站点和产品
    ...generateCRUDPermissions("SITES"),
    ...generateCRUDPermissions("PRODUCTS"),
    ...generateCRUDPermissions("SKUS"),
    ...generateCRUDPermissions("MEDIA"),
    // 业务管理
    ...generateCRUDPermissions("CUSTOMERS"),
    ...generateCRUDPermissions("INQUIRIES"),
    ...generateCRUDPermissions("QUOTATIONS"),
    // 特殊权限
    PERMISSIONS.SITES_MANAGE,
  ],

  [ROLES.DEPT_MANAGER]: [
    // 用户管理
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_EDIT,
    PERMISSIONS.USER_DELETE,
    // 产品管理
    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.PRODUCT_CREATE,
    PERMISSIONS.PRODUCT_EDIT,
    PERMISSIONS.PRODUCT_DELETE,
    PERMISSIONS.SKU_VIEW,
    PERMISSIONS.SKU_CREATE,
    PERMISSIONS.SKU_EDIT,
    PERMISSIONS.SKU_DELETE,
    PERMISSIONS.MEDIA_VIEW,
    PERMISSIONS.MEDIA_CREATE,
    PERMISSIONS.MEDIA_EDIT,
    PERMISSIONS.MEDIA_DELETE,
    // 业务管理
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_EDIT,
    PERMISSIONS.CUSTOMER_DELETE,
    PERMISSIONS.INQUIRY_VIEW,
    PERMISSIONS.INQUIRY_CREATE,
    PERMISSIONS.INQUIRY_EDIT,
    PERMISSIONS.INQUIRY_DELETE,
    PERMISSIONS.QUOTATION_VIEW,
    PERMISSIONS.QUOTATION_CREATE,
    PERMISSIONS.QUOTATION_EDIT,
    PERMISSIONS.QUOTATION_DELETE,
    // 站点查看和编辑
    PERMISSIONS.SITE_VIEW,
    PERMISSIONS.SITE_EDIT,
  ],

  [ROLES.SALESPERSON]: [
    // 客户管理
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_EDIT,
    PERMISSIONS.CUSTOMER_DELETE,
    // 产品查看和创建
    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.PRODUCT_CREATE,
    PERMISSIONS.PRODUCT_EDIT,
    PERMISSIONS.SKU_VIEW,
    // 媒体管理
    PERMISSIONS.MEDIA_VIEW,
    PERMISSIONS.MEDIA_CREATE,
    PERMISSIONS.MEDIA_DELETE,
    // 站点查看
    PERMISSIONS.SITE_VIEW,
    PERMISSIONS.SITECATEGORY_VIEW,
    PERMISSIONS.SITEPRODUCT_VIEW,
    // 询盘和报价
    PERMISSIONS.INQUIRY_VIEW,
    PERMISSIONS.INQUIRY_CREATE,
    PERMISSIONS.INQUIRY_EDIT,
    PERMISSIONS.QUOTATION_VIEW,
    PERMISSIONS.QUOTATION_CREATE,
    PERMISSIONS.QUOTATION_EDIT,
  ],
} as const;

// 辅助函数：生成CRUD权限
function generateCRUDPermissions(resource: string) {
  const upperResource = resource.toUpperCase();
  return [
    `${upperResource}_VIEW`,
    `${upperResource}_CREATE`,
    `${upperResource}_EDIT`,
    `${upperResource}_DELETE`,
  ];
}
