import {
  type ClassDeclaration,
  type Node,
  type ObjectLiteralExpression,
  Scope,
  type SourceFile,
  SyntaxKind,
} from "ts-morph";

const GEN_TAG = "@generated";
const DOC_BLOCK = `/**\n * 🤖 [Auto-Generated] Do not edit this tag to keep updates.\n * ${GEN_TAG}\n */`;

/**
 * 🛠️ 确保 Import 存在
 */
export function ensureImport(
  file: SourceFile,
  moduleSpecifier: string,
  namedImports: string[]
) {
  let decl = file.getImportDeclaration(
    (d) => d.getModuleSpecifierValue() === moduleSpecifier
  );
  if (!decl) {
    decl = file.addImportDeclaration({ moduleSpecifier });
  }
  const existingNamed = decl.getNamedImports().map((n) => n.getName());
  for (const name of namedImports) {
    if (!existingNamed.includes(name)) {
      decl.addNamedImport(name);
    }
  }
}

/**
 * 🛠️ 智能更新对象属性 (用于 Contract)
 */
export function upsertObjectProperty(
  objLiteral: ObjectLiteralExpression,
  key: string,
  value: string
) {
  const prop = objLiteral.getProperty(key);

  // 1. 新增
  if (!prop) {
    objLiteral.addPropertyAssignment({
      name: key,
      initializer: value,
      leadingTrivia: (w) => w.writeLine(DOC_BLOCK),
    });
    console.log(`     ➕ Property: ${key}`);
    return;
  }

  // 2. 检查标记
  if (prop.isKind(SyntaxKind.PropertyAssignment)) {
    // 2.1 类型断言为 PropertyAssignment（确保类型安全）
    const propAssignment = prop;

    // 2.2 获取属性的名称节点（Identifier），这是带有 JSDoc 的节点
    const nameNode = propAssignment.getNameNode();
    if (!nameNode) {
      console.warn(
        `     ⚠️ Property ${key} 无有效名称节点，无法检查自动生成标记`
      );
      return;
    }

    const isGenerated = isAutoGenerated(nameNode);
    console.log(`     🔍 Property ${key} is auto generated: ${isGenerated}`);

    if (isGenerated) {
      if (prop.getInitializer()?.getText() !== value) {
        prop.setInitializer(value);
        console.log(`     🔄 Updated: ${key}`);
      }
    } else {
      console.log(`     🛡️ Skipped (Custom): ${key}`);
    }
  }
}

/**
 * 🛠️ 智能更新类方法 (用于 Service/Controller)
 */
export function upsertMethod(
  classDec: ClassDeclaration,
  name: string,
  body: string,
  params: { name: string; type: string }[] = [],
  returnType?: string
) {
  const method = classDec.getMethod(name);

  // 1. 新增
  if (!method) {
    const m = classDec.addMethod({
      name,
      parameters: params,
      returnType,
      isAsync: true,
      scope: Scope.Public,
      statements: body,
    });
    m.addJsDoc(DOC_BLOCK);
    console.log(`     ➕ Method: ${name}`);
    return;
  }

  // 2. 检查标记
  const isGenerated = method
    .getJsDocs()
    .some((d) => d.getInnerText().includes(GEN_TAG));

  if (isGenerated) {
    method.setBodyText(body);
    // 更新参数类型以防 Schema 变更
    method.getParameters().forEach((p) => p.remove());
    params.forEach((p) => method.addParameter(p));
    if (returnType) method.setReturnType(returnType);
    console.log(`     🔄 Updated: ${name}`);
  } else {
    console.log(`     🛡️ Skipped (Custom): ${name}`);
  }
}
/**
 * 工具方法 1：最新版 ts-morph 兼容 - 提取节点前置 JSDoc 纯文本
 * @param node 任意节点（Identifier/PropertyName 等）
 * @returns 纯净的 JSDoc 文本
 */
function getLeadingJSDocText(node: Node): string {
  // 1. 获取节点所在源文件的完整文本
  const fullText = node.getSourceFile().getFullText();

  // 2. 获取节点的起始位置（偏移量）
  const nodeStart = node.getPos();

  // 3. 截取节点前方的所有文本（即前置 trivia 内容）
  const leadingText = fullText.slice(0, nodeStart);

  // 4. 正则匹配最后一个 JSDoc 注释（/** ... */ 格式，确保是节点直接前置的注释）
  const jsDocMatches = leadingText.match(/\/\*\*[\s\S]*?\*\//g);
  if (!jsDocMatches || jsDocMatches.length === 0) return "";

  // 5. 取最后一个匹配结果（最靠近节点的 JSDoc）
  const lastJsDoc = jsDocMatches.at(-1);

  // 6. 去除注释标记，提取纯文本
  return lastJsDoc
    ? lastJsDoc
        .replace(/^\/\*\*+/, "")
        .replace(/\*+\/$/, "")
        .replace(/^\s*\*\s*/gm, "")
        .trim()
    : "";
}

/**
 * 工具方法 2：判断节点是否为自动生成（前置 JSDoc 包含 GEN_TAG）
 * @param node 任意节点（Identifier/PropertyName 等）
 * @returns 是否为自动生成
 */
function isAutoGenerated(node: Node): boolean {
  const jsDocText = getLeadingJSDocText(node);
  // 精准匹配 @auto-gen 标签，避免误判
  return /@auto-gen\b/.test(jsDocText);
}
