export declare const env: Readonly<{
  EMAIL_PORT?: number | undefined;
  EMAIL_USER?: string | undefined;
  EMAIL_PASSWORD?: string | undefined;
  EMAIL_FROM?: string | undefined;
  ACCESS_KEY_ID?: string | undefined;
  SECRET_ACCESS_KEY?: string | undefined;
  BUCKET?: string | undefined;
  REGION?: string | undefined;
  ENDPOINT?: string | undefined;
  DOMAIN?: string | undefined;
  NODE_ENV: "development" | "test" | "production";
  APP_PORT: number;
  SECRET: string;
  DATABASE_URL: string;
  BETTER_AUTH_SECRET: string;
  BETTER_AUTH_BASE_URL: string;
  GITHUB_CLIENT_ID: string;
  GITHUB_CLIENT_SECRET: string;
  EMAIL_HOST: string;
  ALIBABA_CLOUD_ACCESS_KEY_ID: string;
  ALIBABA_CLOUD_ACCESS_KEY_SECRET: string;
  AUTH_COOKIE: string;
  SERVER_URL_KEY: string;
  NEXT_PUBLIC_API_URL: string;
}>;
